version: '3.8'

services:
  solidity-co-pilots:
    build: .
    container_name: solidity_co_pilots
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
    security_opt:
      - no-new-privileges:true
